- .gitattributes
- README.md
- appveyor.yml
- recipe/meta.yaml
Also re-rendered with conda-smithy 1.6.0.
> Update to v1.4.2

- README.md
- recipe/meta.yaml
Includes PR ( https://github.com/conda-forge/boto3-feedstock/pull/4 ).
> Release 1.4.4

- recipe/meta.yaml
ref https://github.com/boto/boto3/blob/1.5.14/setup.py#L17-L19
increment build to 2
replaces #11
> fix requirement bounds to match upstream setup.py

- recipe/meta.yaml
> Update to v1.5.18

- recipe/meta.yaml
add entries to about section
change from build to host as recommended when using conda build 3.
> sync recipe with AnacondaRecipes

- recipe/meta.yaml
> Update to v1.7.46

- recipe/meta.yaml
> Update to v1.7.47

- recipe/meta.yaml
> Update to v1.7.48

- recipe/meta.yaml
> Update to v1.7.49

- recipe/meta.yaml
> Update to v1.7.50

- recipe/meta.yaml
> Update to v1.7.51

- recipe/meta.yaml
> Update to v1.7.52

- recipe/meta.yaml
> Update to v1.7.53

- recipe/meta.yaml
> Update to 1.9.21

- recipe/meta.yaml
Checklist
should need less manual housekeeping
> Use jinja math for botocore requirement

- recipe/meta.yaml
> Update to 1.9.83

- recipe/meta.yaml
> Update to 1.9.130

- recipe/meta.yaml
> update to 1.12.9

- recipe/meta.yaml
> update to 1.12.23

- recipe/meta.yaml
> update to 1.12.33

- recipe/meta.yaml
> update to 1.12.42

- recipe/meta.yaml
> update to v1.34.91

- recipe/meta.yaml
there were 2 releases today, bot will probably skip this one
Checklist
> update to v1.35.75

- recipe/meta.yaml
> update to v1.35.78

- recipe/meta.yaml
Checklist
bot will probably miss this one
> update to v1.35.79

- recipe/meta.yaml
Checklist
#1671 since the bot has been slow
> updated v1.35.81

- .gitignore
- recipe/meta.yaml
Checklist
the bot will probably miss this version
> update to v1.37.3

- recipe/meta.yaml
bot will miss this version
Checklist
> update to v1.37.26

- recipe/meta.yaml
> test returning to usual source url

- recipe/meta.yaml
> return to usual source url

- recipe/meta.yaml
bot will probably miss this version
Checklist
> update to v1.40.17

- recipe/meta.yaml
> updated v1.40.38
